=== KayaTyan/OstranautsRuKaya/complete/data/data/schemas/conditions-schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "array",
    "items": {
        "type": "object",
        "additionalProperties": false,
        "properties": {
            "strName": {
                "type": "string"
            },
            "strNameFriendly": {
                "type": "string"
            },
            "strColor": {
                "type": "string"
            },
            "strDesc": {
                "type": "string"
            },
            "bResetTimer": {
                "type": "boolean"
            },
            "nDisplaySelf": {
                "type": "integer"
            },
            "nDisplayOther": {
                "type": "integer"
            },
            "bFatal": {
                "type": "boolean"
            },
            "bRemoveAll": {
                "type": "boolean"
            },
            "aNext": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "fDuration": {
                "type": "number"
            },
            "bRemoveOnLoad": {
                "type": "boolean"
            },
            "aPer": {
                "type": "array",
                "items": {
                    "type": "string"
                }
            },
            "fClampMax": {
                "type": "number"
            },
            "bKO": {
                "type": "boolean"
            },
            "bAlert": {
                "type": "boolean"
            },
            "strAnti": {
                "type": "string"
            },
            "bPersists": {
                "type": "boolean"
            },
            "pairFaceSprite": {
                "type": "object",
                "additionalProperties": false,
                "properties": {
                    "nValue": {
                        "type": "integer"
                    },
                    "strName": {
                        "type": "string"
                    }
                },
                "required": [
                    "nValue",
                    "strName"
                ]
            },
            "bRoom": {
                "type": "boolean"
            },
            "strCTImmune": {
                "type": "string"
            }
        },
        "required": [
            "strColor",
            "strDesc",
            "strName",
            "strNameFriendly"
        ]
    }
}

=== KayaTyan/OstranautsRuKaya/complete/data/conditions/conditions_stakes_follow.json
[
    { "strName" : "IsSTKFollow_Fail_Cooldown", "strNameFriendly" : "STKFollow Fail Cooldown", "strColor" : "Neutral", "strDesc"  : "[us] tried to STKFollow and can't try it again yet.", "bResetTimer" : true, "nDisplaySelf" : 0, "nDisplayOther" : 0, "fDuration" : 0.1 },
    { "strName" : "IsSTKFollow_Fail_Avoid", "strNameFriendly" : "STKFollow Fail Soft", "strColor" : "Neutral", "strDesc"  : "[us] used a soft fail in STKFollow to avoid a hard fail and can't use it again yet.", "bResetTimer" : true, "nDisplaySelf" : 0, "nDisplayOther" : 0, "fDuration" : 0.1 },
    { "strName" : "IsSTKFollow_Chitchat_Trait_Used", "strNameFriendly" : "STKFollow Chitchat Trait Used", "strColor" : "Neutral", "strDesc"  : "[us] used a trait chitchat move in STKFollow and can't use it again yet.", "bResetTimer" : true, "nDisplaySelf" : 0, "nDisplayOther" : 0, "fDuration" : 0.1 }
]
